### ISSUE TITLE
Missing makefile in Binary Pathfinder

### ISSUE THREAD

**Issue by AythaE** [aquirin/pathfinder#1]
Hi,
I'm trying to apply a pathfinder algorithm to a directed graph, according to your [web page](http://aquirin.ovh.org/research/mstpathfinder.html) the better algorithm to do that is the Binary Pathfinder, which is also the only one without a makefile.

I had tried to create one using the others as it could be seen in the following code

```
#
#	MAKEFILE
#

# -g: Compilar
# -c: Permitir depuracion posterior

# For "valgrind -v --leak-check=yes --show-reachable=yes "
#CFLAGS =  -g -c -O0

# Normal way
CFLAGS = -c -O3

# Ficheros .c

C = binary.c routines.c

# Ficheros .o

O = binary.o routines.o

# Compilacion inicial

.c.o:
	gcc $(CFLAGS) $(C)

# Compilacion final
pathfinder:	binary.o $(O)
	gcc -o binary_pathfinder $(O) -lm

clean:
	rm -rf binary_pathfinder *.o

```

But i got several errors with the `routines.c` file:

```
$ make
gcc -g -c -O3 binary.c routines.c
routines.c: In function ‘alead’:
routines.c:288:9: warning: incompatible implicit declaration of built-in function ‘fabs’
  return fabs(b-a)*rand()/(RAND_MAX+1.0)+MIN(a,b);
         ^
routines.c: In function ‘aleado’:
routines.c:293:9: warning: incompatible implicit declaration of built-in function ‘fabs’
  return fabs(b-a)*rand()/(RAND_MAX)+MIN(a,b);
         ^
routines.c: In function ‘rnd’:
routines.c:353:9: warning: incompatible implicit declaration of built-in function ‘floor’
  return floor(f*g+0.5)/g;   // Comportement OK : rnd(-2.5,0) = -2
         ^
routines.c: In function ‘rnd_sup’:
routines.c:363:9: warning: incompatible implicit declaration of built-in function ‘ceil’
  return ceil(f*g)/g;
         ^
routines.c: In function ‘rnd_inf’:
routines.c:373:9: warning: incompatible implicit declaration of built-in function ‘floor’
  return floor(f*g)/g;
         ^
routines.c: At top level:
routines.c:913:7: error: conflicting types for ‘getline’
 char* getline(FILE* in, int *size)
       ^
In file included from base.h:5:0,
                 from routines.c:5:
/usr/include/stdio.h:678:20: note: previous declaration of ‘getline’ was here
 extern _IO_ssize_t getline (char **__restrict __lineptr,
                    ^
makefile:25: recipe for target 'binary.o' failed
make: *** [binary.o] Error 1
```

I'm using GNU Make 4.0 and gcc 4.9.2 on a Debian 8.7 machine.

Thanks in advance.

**Comment by aquirin** [comment]
Hi!

It seems an easy issue, just based on the signature of a single function
(the others are warnings ), unfortunately I don't have access to a Linux
box right now but I will try tomorrow

**Comment by aquirin** [comment]
I have updated the files of all pathfinder variants so that they compile with the -Wall option. I have also added a Makefile for the Binary Pathfinder algorithm. Tested successfully with gcc 6.2.0 but it should work with gcc 4.9.2 too. Do not hesitate to comment if the new version is not working.

Thank you for using Pathfinder code.

**Comment by AythaE** [comment]
The binary pathfinder makefile has worked for me also.
Thanks you for your time!
